
EXPENSES_MINIMUM_VALUE = 700
EXPENSES_EXTRA_MINIMUM = 0.4
EXPENSES_EXTRA_OFFSET = 0.25

GREEDINESS_AVERAGE=1.1
GREEDINESS_STDEV=0.1

INCOME_MULTIPLICATION_FACTOR=1.0

HOUSE_SEARCH_OBFUSCATION_FACTOR=0.6
HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL=0.6
HOUSE_PRICE_REDUCTION_FACTOR=0.01
INITIAL_WEALTH_PER_PERCENTILE=30
INITIAL_WEALTH_PER_AGE=10
