MAX_BUCKET_SIZE = 30
NUMBER_OF_HOUSEHOLDS = 7500
NUMBER_OF_STEPS = 100
STARTING_GOV_WEALTH_PER_CAPITA = 100000.0
STARTING_COMPANY_WEALTH_PER_CAPITA = 60000.0
STARTING_BANK_WEALTH_PER_CAPITA = 67000.0
STARTING_CONSTRUCTION_SECTOR_WEALTH_PER_CAPITA = 35000.0
STARTING_GOV_WEALTH = STARTING_GOV_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
STARTING_COMPANY_WEALTH = STARTING_COMPANY_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
STARTING_BANK_WEALTH = STARTING_BANK_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
STARTING_CONSTRUCTION_SECTOR_WEALTH = STARTING_CONSTRUCTION_SECTOR_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
INTEREST_RATE = 0.015
LTV = 0.8
DSTI = 0.35
EXPENSES_MINIMUM_VALUE = 400
EXPENSES_EXTRA_MINIMUM = 0.5
EXPENSES_EXTRA_OFFSET = 0.35
IRS = 0.3
VAT = 0.15
IRC = 0.2
FRACTION_OF_HOMEOWNERS = 0.7
FRACTION_OF_DOUBLE_OWNERS = 0.3

TotalTheoreticalNumberOfHouses = 1191363
# TheoreticalNumberOfHousesInGrandeLisboa = 858646
TheoreticalNumberOfHousesInAmadora = 73513
TheoreticalNumberOfHousesInCascais = 86465
TheoreticalNumberOfHousesInLisboa = 242044
TheoreticalNumberOfHousesInLoures =  81552
TheoreticalNumberOfHousesInMafra = 33152
TheoreticalNumberOfHousesInOdivelas = 60119
TheoreticalNumberOfHousesInOeiras = 73013
TheoreticalNumberOfHousesInSintra = 153147
TheoreticalNumberOfHousesInVilaFrancaDeXira = 55641
TheoreticalNumberOfHousesInAlcochete = 7411
TheoreticalNumberOfHousesInAlmada = 75485
TheoreticalNumberOfHousesInBarreiro = 34346
TheoreticalNumberOfHousesInMoita = 27489
TheoreticalNumberOfHousesInMontijo = 22104
TheoreticalNumberOfHousesInPalmela = 26622
TheoreticalNumberOfHousesInSeixal = 67534
TheoreticalNumberOfHousesInSesimbra = 20557
TheoreticalNumberOfHousesInSetubal = 51169

NUMBER_OF_HOUSES=NUMBER_OF_HOUSEHOLDS
# NUMBER_OF_HOUSES_IN_GrandeLisboa = (TheoreticalNumberOfHousesInGrandeLisboa / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Amadora = (TheoreticalNumberOfHousesInAmadora / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Cascais = (TheoreticalNumberOfHousesInCascais / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Lisboa = (TheoreticalNumberOfHousesInLisboa / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Loures = (TheoreticalNumberOfHousesInLoures / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Mafra = (TheoreticalNumberOfHousesInMafra / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Odivelas = (TheoreticalNumberOfHousesInOdivelas / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Oeiras = (TheoreticalNumberOfHousesInOeiras / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Sintra = (TheoreticalNumberOfHousesInSintra / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_VilaFrancaDeXira = (TheoreticalNumberOfHousesInVilaFrancaDeXira / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Alcochete = (TheoreticalNumberOfHousesInAlcochete / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Almada = (TheoreticalNumberOfHousesInAlmada / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Barreiro = (TheoreticalNumberOfHousesInBarreiro / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Moita = (TheoreticalNumberOfHousesInMoita / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Montijo = (TheoreticalNumberOfHousesInMontijo / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Palmela = (TheoreticalNumberOfHousesInPalmela / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Seixal = (TheoreticalNumberOfHousesInSeixal / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Sesimbra = (TheoreticalNumberOfHousesInSesimbra / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Setubal = (TheoreticalNumberOfHousesInSetubal / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 

FIRST_QUARTILE_RENT_IN_Amadora = 7.35
FIRST_QUARTILE_RENT_IN_Cascais = 9.42
FIRST_QUARTILE_RENT_IN_Lisboa = 9.86
FIRST_QUARTILE_RENT_IN_Loures = 6.31
FIRST_QUARTILE_RENT_IN_Mafra = 5.27
FIRST_QUARTILE_RENT_IN_Odivelas = 6.59
FIRST_QUARTILE_RENT_IN_Oeiras = 8.98
FIRST_QUARTILE_RENT_IN_Sintra = 6.00
FIRST_QUARTILE_RENT_IN_VilaFrancaDeXira = 5.77
FIRST_QUARTILE_RENT_IN_Alcochete = 5.65
FIRST_QUARTILE_RENT_IN_Almada = 7.04
FIRST_QUARTILE_RENT_IN_Barreiro = 6.27
FIRST_QUARTILE_RENT_IN_Moita = 5.38
FIRST_QUARTILE_RENT_IN_Montijo = 5.76
FIRST_QUARTILE_RENT_IN_Palmela = 5.23
FIRST_QUARTILE_RENT_IN_Seixal = 6.25
FIRST_QUARTILE_RENT_IN_Sesimbra = 5.29
FIRST_QUARTILE_RENT_IN_Setubal = 5.65




THIRD_QUARTILE_RENT_IN_Amadora = 11.6
THIRD_QUARTILE_RENT_IN_Cascais = 16.38
THIRD_QUARTILE_RENT_IN_Lisboa = 16.67
THIRD_QUARTILE_RENT_IN_Loures = 10.67
THIRD_QUARTILE_RENT_IN_Mafra = 9.91
THIRD_QUARTILE_RENT_IN_Odivelas = 11.07
THIRD_QUARTILE_RENT_IN_Oeiras = 14.16
THIRD_QUARTILE_RENT_IN_Sintra = 10.0
THIRD_QUARTILE_RENT_IN_VilaFrancaDeXira = 9.16
THIRD_QUARTILE_RENT_IN_Alcochete = 9.45
THIRD_QUARTILE_RENT_IN_Almada = 11.9
THIRD_QUARTILE_RENT_IN_Barreiro = 9.52
THIRD_QUARTILE_RENT_IN_Moita = 8.73
THIRD_QUARTILE_RENT_IN_Montijo = 8.93
THIRD_QUARTILE_RENT_IN_Palmela = 8.33
THIRD_QUARTILE_RENT_IN_Seixal = 9.86
THIRD_QUARTILE_RENT_IN_Sesimbra = 8.65
THIRD_QUARTILE_RENT_IN_Setubal = 9.61

FIRST_QUARTILE_SALES_IN_Amadora = 1686
FIRST_QUARTILE_SALES_IN_Cascais = 2692
FIRST_QUARTILE_SALES_IN_Lisboa = 3015
FIRST_QUARTILE_SALES_IN_Loures = 1667
FIRST_QUARTILE_SALES_IN_Mafra = 1593
FIRST_QUARTILE_SALES_IN_Odivelas = 1939
FIRST_QUARTILE_SALES_IN_Oeiras = 2485
FIRST_QUARTILE_SALES_IN_Sintra = 1531
FIRST_QUARTILE_SALES_IN_VilaFrancaDeXira = 1375
FIRST_QUARTILE_SALES_IN_Alcochete = 1424
FIRST_QUARTILE_SALES_IN_Almada = 1753
FIRST_QUARTILE_SALES_IN_Barreiro = 1244
FIRST_QUARTILE_SALES_IN_Moita = 985
FIRST_QUARTILE_SALES_IN_Montijo = 1364
FIRST_QUARTILE_SALES_IN_Palmela = 1287
FIRST_QUARTILE_SALES_IN_Seixal = 1480
FIRST_QUARTILE_SALES_IN_Sesimbra = 1571
FIRST_QUARTILE_SALES_IN_Setubal = 1300

THIRD_QUARTILE_SALES_IN_Amadora = 2414
THIRD_QUARTILE_SALES_IN_Cascais = 4667
THIRD_QUARTILE_SALES_IN_Lisboa = 4977
THIRD_QUARTILE_SALES_IN_Loures = 2662
THIRD_QUARTILE_SALES_IN_Mafra = 2548
THIRD_QUARTILE_SALES_IN_Odivelas = 2819
THIRD_QUARTILE_SALES_IN_Oeiras = 3626
THIRD_QUARTILE_SALES_IN_Sintra = 2137
THIRD_QUARTILE_SALES_IN_VilaFrancaDeXira = 2100
THIRD_QUARTILE_SALES_IN_Alcochete = 2421
THIRD_QUARTILE_SALES_IN_Almada = 2679
THIRD_QUARTILE_SALES_IN_Barreiro = 1763
THIRD_QUARTILE_SALES_IN_Moita = 1556
THIRD_QUARTILE_SALES_IN_Montijo = 2006
THIRD_QUARTILE_SALES_IN_Palmela = 1839
THIRD_QUARTILE_SALES_IN_Seixal = 2099
THIRD_QUARTILE_SALES_IN_Sesimbra = 2428
THIRD_QUARTILE_SALES_IN_Setubal = 2020

@enum HouseLocation begin
    Amadora = 1
    Cascais = 2
    Lisboa = 3
    Loures = 4
    Mafra = 5
    Odivelas = 6
    Oeiras = 7
    Sintra = 8
    VilaFrancaDeXira = 9
    Alcochete = 10
    Almada = 11
    Barreiro = 12
    Moita = 13
    Montijo = 14
    Palmela = 15
    Seixal =  16
    Sesimbra = 17
    Setubal = 18
end

color_map = Dict(
    Amadora => :red,
    Cascais => :blue,
    Lisboa => :green,
    Loures => :yellow,
    Mafra => :purple,
    Odivelas => :orange,
    Oeiras => :pink,
    Sintra => :brown,
    VilaFrancaDeXira => :cyan,
    Alcochete => :magenta,
    Almada => :lime,
    Barreiro => :navy,
    Moita => :teal,
    Montijo => :olive,
    Palmela => :maroon,
    Seixal => :aqua,
    Sesimbra => :fuchsia,
    Setubal => :gold
)

firstQuartileHousePricesPerRegion = Dict(
    Amadora          => 1686,
    Cascais          => 2692,
    Lisboa           => 3015,
    Loures           => 1667,
    Mafra            => 1593,
    Odivelas         => 1939,
    Oeiras           => 2485,
    Sintra           => 1531,
    VilaFrancaDeXira => 1375,
    Alcochete        => 1424,
    Almada           => 1753,
    Barreiro         => 1244,
    Moita            => 985,
    Montijo          => 1364,
    Palmela          => 1287,
    Seixal           => 1480,
    Sesimbra         => 1571,
    Setubal          => 1300,
)

thirdQuartileHousePricesPerRegion = Dict(
    Amadora          => 2414,
    Cascais          => 4667,
    Lisboa           => 4977,
    Loures           => 2662,
    Mafra            => 2548,
    Odivelas         => 2819,
    Oeiras           => 3626,
    Sintra           => 2137,
    VilaFrancaDeXira => 2100,
    Alcochete        => 2421,
    Almada           => 2679,
    Barreiro         => 1763,
    Moita            => 1556,
    Montijo          => 2006,
    Palmela          => 1839,
    Seixal           => 2099,
    Sesimbra         => 2428,
    Setubal          => 2020,
)