include("types.jl")
include("calibrationTable.jl")

MAX_BUCKET_SIZE = 100
NUMBER_OF_HOUSEHOLDS = 7500
NUMBER_OF_STEPS = 500
STARTING_GOV_WEALTH_PER_CAPITA = 100000.0
STARTING_COMPANY_WEALTH_PER_CAPITA = 60000.0
STARTING_BANK_WEALTH_PER_CAPITA = 67000.0
STARTING_CONSTRUCTION_SECTOR_WEALTH_PER_CAPITA = 5000.0
STARTING_GOV_WEALTH = STARTING_GOV_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
STARTING_COMPANY_WEALTH = STARTING_COMPANY_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
STARTING_BANK_WEALTH = STARTING_BANK_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
STARTING_CONSTRUCTION_SECTOR_WEALTH = STARTING_CONSTRUCTION_SECTOR_WEALTH_PER_CAPITA * NUMBER_OF_HOUSEHOLDS
INTEREST_RATE = 0.015
LTV = 0.75
DSTI = 0.4
IRS = 0.2
VAT = 0.15
MAX_EFFORT_FOR_RENT = 0.5
FRACTION_OF_HOMEOWNERS = 0.7
FRACTION_OF_DOUBLE_OWNERS = 0.3
CONSTRUCTION_DELAY_MIN = 24
CONSTRUCTION_DELAY_MAX = 48
CONSTRUCTION_COSTS_MIN = 1500 # to be multiplied by the area of the house
CONSTRUCTION_COSTS_MAX = 2500 # to be multiplied by the area of the house
CONSTRUCTION_TIME_MIN = 12
CONSTRUCTION_TIME_MAX = 18
CONSTRUCTION_VAT = 0.23
LAND_COSTS = 1000 # TODO: this should be a dict, different price for each region
PROJECT_COST_MULTIPLIER = 1.1

INITIAL_WEALTH_MULTIPLICATION_BASE = 1.0
INITIAL_WEALTH_MULTIPLICATION_ROOF = 4.0
INITIAL_WEALTH_MULTIPLICATION_AVERAGE = 6.0
INITIAL_WEALTH_MULTIPLICATION_STDEV = 4.0
CONSUMER_SURPLUS_MIN = 0.94
CONSUMER_SURPLUS_MAX = 1.05
CONSTRUCTION_SECTOR_MARKUP = 1.2


TotalTheoreticalNumberOfHouses = 1191363
# TheoreticalNumberOfHousesInGrandeLisboa = 858646
TheoreticalNumberOfHousesInAmadora = 73513
TheoreticalNumberOfHousesInCascais = 86465
TheoreticalNumberOfHousesInLisboa = 242044
TheoreticalNumberOfHousesInLoures =  81552
TheoreticalNumberOfHousesInMafra = 33152
TheoreticalNumberOfHousesInOdivelas = 60119
TheoreticalNumberOfHousesInOeiras = 73013
TheoreticalNumberOfHousesInSintra = 153147
TheoreticalNumberOfHousesInVilaFrancaDeXira = 55641
TheoreticalNumberOfHousesInAlcochete = 7411
TheoreticalNumberOfHousesInAlmada = 75485
TheoreticalNumberOfHousesInBarreiro = 34346
TheoreticalNumberOfHousesInMoita = 27489
TheoreticalNumberOfHousesInMontijo = 22104
TheoreticalNumberOfHousesInPalmela = 26622
TheoreticalNumberOfHousesInSeixal = 67534
TheoreticalNumberOfHousesInSesimbra = 20557
TheoreticalNumberOfHousesInSetubal = 51169

NUMBER_OF_HOUSES=NUMBER_OF_HOUSEHOLDS

# TODO: region hack
MODEL_SCALE = NUMBER_OF_HOUSES / TheoreticalNumberOfHousesInLisboa
# MODEL_SCALE = NUMBER_OF_HOUSES / TotalTheoreticalNumberOfHouses

# NUMBER_OF_HOUSES_IN_GrandeLisboa = (TheoreticalNumberOfHousesInGrandeLisboa / TotalTheoreticalNumberOfHouses) * NUMBER_OF_HOUSES 
NUMBER_OF_HOUSES_IN_Amadora = TheoreticalNumberOfHousesInAmadora * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Cascais = TheoreticalNumberOfHousesInCascais * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Lisboa = TheoreticalNumberOfHousesInLisboa * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Loures = TheoreticalNumberOfHousesInLoures * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Mafra = TheoreticalNumberOfHousesInMafra * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Odivelas = TheoreticalNumberOfHousesInOdivelas * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Oeiras = TheoreticalNumberOfHousesInOeiras * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Sintra = TheoreticalNumberOfHousesInSintra * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_VilaFrancaDeXira = TheoreticalNumberOfHousesInVilaFrancaDeXira * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Alcochete = TheoreticalNumberOfHousesInAlcochete * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Almada = TheoreticalNumberOfHousesInAlmada * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Barreiro = TheoreticalNumberOfHousesInBarreiro * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Moita = TheoreticalNumberOfHousesInMoita * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Montijo = TheoreticalNumberOfHousesInMontijo * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Palmela = TheoreticalNumberOfHousesInPalmela * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Seixal = TheoreticalNumberOfHousesInSeixal * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Sesimbra = TheoreticalNumberOfHousesInSesimbra * MODEL_SCALE 
NUMBER_OF_HOUSES_IN_Setubal = TheoreticalNumberOfHousesInSetubal * MODEL_SCALE 

FIRST_QUARTILE_RENT_MAP = Dict(
    Amadora => 7.14,
    Cascais => 8.62,
    Lisboa => 8.89,
    Loures => 5.94,
    Mafra => 5.03,
    Odivelas => 6.12,
    Oeiras => 8.05,
    Sintra => 5.67,
    VilaFrancaDeXira => 5.56,
    Alcochete => 5.35,
    Almada => 6.75,
    Barreiro => 5.80,
    Moita => 4.99,
    Montijo => 5.26,
    Palmela => 4.74,
    Seixal => 5.52,
    Sesimbra => 4.22,
    Setubal => 5.17,
)

MEDIAN_RENT_MAP = Dict(
    Amadora => 8.85,
    Cascais => 10.95,
    Lisboa => 11.24,
    Loures => 7.90,
    Mafra => 6.94,
    Odivelas => 8.43,
    Oeiras =>.10,
    Sintra => 7.46,
    VilaFrancaDeXira => 7.09,
    Alcochete => 6.74,
    Almada => 8.58,
    Barreiro => 7.24,
    Moita => 6.21,
    Montijo => 6.48,
    Palmela => 6.03,
    Seixal => 7.01,
    Sesimbra => 6.07,
    Setubal => 6.85,
)

THIRD_QUARTILE_RENT_MAP = Dict(
    Amadora => 10.66,
    Cascais => 13.84,
    Lisboa => 13.87,
    Loures => 9.75,
    Mafra => 8.92,
    Odivelas => 10.15,
    Oeiras => 12.17,
    Sintra => 9.10,
    VilaFrancaDeXira => 8.51,
    Alcochete => 8.66,
    Almada => 10.59,
    Barreiro => 8.66,
    Moita => 7.78,
    Montijo => 7.58,
    Palmela => 7.57,
    Seixal => 8.50,
    Sesimbra => 7.78,
    Setubal => 8.42,
)

FIRST_QUARTILE_SALES_MAP = Dict(
    Amadora => 1408,
    Cascais => 2133,
    Lisboa => 2523,
    Loures => 1403,
    Mafra => 1212,
    Odivelas => 1603,
    Oeiras => 1995,
    Sintra => 1157,
    VilaFrancaDeXira => 1101,
    Alcochete => 1211,
    Almada => 1466,
    Barreiro => 908,
    Moita => 733,
    Montijo => 1023,
    Palmela => 988,
    Seixal => 1117,
    Sesimbra => 1205,
    Setubal => 1014,
)

MEDIAN_SALES_MAP = Dict(
    Amadora => 1723,
    Cascais => 2776,
    Lisboa => 3333,
    Loures => 1820,
    Mafra => 1600,
    Odivelas => 2057,
    Oeiras => 2440,
    Sintra => 1441,
    VilaFrancaDeXira => 1383,
    Alcochete => 1525,
    Almada => 1801,
    Barreiro => 1136,
    Moita => 952,
    Montijo => 1334,
    Palmela => 1198,
    Seixal => 1380,
    Sesimbra => 1456,
    Setubal => 1307,
)

THIRD_QUARTILE_SALES_MAP = Dict(
    Amadora => 2060,
    Cascais => 3644,
    Lisboa => 4392,
    Loures => 2296,
    Mafra => 1999,
    Odivelas => 2464,
    Oeiras => 2957,
    Sintra => 1703,
    VilaFrancaDeXira => 1704,
    Alcochete => 2051,
    Almada => 2177,
    Barreiro => 1341,
    Moita => 1190,
    Montijo => 1602,
    Palmela => 1426,
    Seixal => 1667,
    Sesimbra => 1799,
    Setubal => 1610,
)

color_map = Dict(
    Amadora => :red,
    Cascais => :blue,
    Lisboa => :green,
    Loures => :yellow,
    Mafra => :purple,
    Odivelas => :orange,
    Oeiras => :pink,
    Sintra => :brown,
    VilaFrancaDeXira => :cyan,
    Alcochete => :magenta,
    Almada => :lime,
    Barreiro => :navy,
    Moita => :teal,
    Montijo => :olive,
    Palmela => :maroon,
    Seixal => :aqua,
    Sesimbra => :fuchsia,
    Setubal => :gold
)

Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_1 = 336274
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Alcochete = 1699
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Almada = 22459
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Amadora = 22151
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Barreiro = 10183
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Cascais = 23431
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Lisboa =  85477
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Loures =  20967
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Mafra = 7359
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Moita = 7285
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Montijo = 5440
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Odivelas = 15483
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Oeiras = 22114
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Palmela = 6195
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Seixal = 16387
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Sesimbra = 4636
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Setubal = 13899
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Sintra = 37771
Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_VilaFrancaDeXira = 13338
Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_2 = 392111
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Alcochete = 2289
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Almada = 25601
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Amadora = 24547
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Barreiro = 12161
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Cascais = 27793
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Lisboa =  78584
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Loures =  27299
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Mafra = 10276
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Moita = 9270
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Montijo = 7231
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Odivelas = 19776
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Oeiras = 23966
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Palmela = 8843
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Seixal = 23196
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Sesimbra = 6742
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Setubal = 17253
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Sintra = 48985
Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_VilaFrancaDeXira = 18299
Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_3 = 238291
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Alcochete = 1675
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Almada = 14318
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Amadora = 14246
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Barreiro = 6769
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Cascais = 17047
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Lisboa =  39037
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Loures =  17089
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Mafra = 7544
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Moita = 5879
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Montijo = 4974
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Odivelas = 12703
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Oeiras = 13479
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Palmela = 5853
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Seixal = 14841
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Sesimbra = 4644
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Setubal = 10598
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Sintra = 34425
Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_VilaFrancaDeXira = 13170
Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_4 = 160982
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Alcochete = 1347
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Almada = 9462
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Amadora = 8682
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Barreiro = 3881
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Cascais = 12688
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Lisboa =  26629
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Loures =  11535
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Mafra = 6060
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Moita = 3610
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Montijo = 3277
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Odivelas = 8843
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Oeiras = 9703
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Palmela = 4318
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Seixal = 9630
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Sesimbra = 3378
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Setubal = 6954
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Sintra = 22670
Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_VilaFrancaDeXira = 8315
Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_GT_5 = 65326
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Alcochete = 427
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Almada = 3852
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Amadora = 3913
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Barreiro = 1372
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Cascais = 5525
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Lisboa =  12844
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Loures =  4812
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Mafra = 1970
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Moita = 1462
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Montijo = 1233
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Odivelas = 3334
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Oeiras = 3764
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Palmela = 1569
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Seixal = 3615
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Sesimbra = 1164
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Setubal = 2525
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Sintra = 9371
Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_VilaFrancaDeXira = 2574


TOTAL_HOUSEHOLDS_WITH_SIZE_1 = Int64(round(MODEL_SCALE * Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_1))

HOUSEHOLDS_WITH_SIZE_1_MAP = Dict(
    Alcochete => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Alcochete)),
    Almada => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Almada)),
    Amadora => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Amadora)),
    Barreiro => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Barreiro)),
    Cascais => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Cascais)),
    Lisboa => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Lisboa)),
    Loures => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Loures)),
    Mafra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Mafra)),
    Moita => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Moita)),
    Montijo => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Montijo)),
    Odivelas => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Odivelas)),
    Oeiras => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Oeiras)),
    Palmela => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Palmela)),
    Seixal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Seixal)),
    Sesimbra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Sesimbra)),
    Setubal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Setubal)),
    Sintra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_Sintra)),
    VilaFrancaDeXira => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_1_IN_VilaFrancaDeXira)),
)

TOTAL_HOUSEHOLDS_WITH_SIZE_2 = Int64(round(MODEL_SCALE * Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_2))
HOUSEHOLDS_WITH_SIZE_2_MAP = Dict(
    Alcochete => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Alcochete)),
    Almada => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Almada)),
    Amadora => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Amadora)),
    Barreiro => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Barreiro)),
    Cascais => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Cascais)),
    Lisboa => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Lisboa)),
    Loures => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Loures)),
    Mafra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Mafra)),
    Moita => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Moita)),
    Montijo => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Montijo)),
    Odivelas => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Odivelas)),
    Oeiras => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Oeiras)),
    Palmela => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Palmela)),
    Seixal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Seixal)),
    Sesimbra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Sesimbra)),
    Setubal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Setubal)),
    Sintra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_Sintra)),
    VilaFrancaDeXira => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_2_IN_VilaFrancaDeXira)),
)

TOTAL_HOUSEHOLDS_WITH_SIZE_3 = Int64(round(MODEL_SCALE * Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_3))
HOUSEHOLDS_WITH_SIZE_3_MAP = Dict(
    Alcochete => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Alcochete)),
    Almada => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Almada)),
    Amadora => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Amadora)),
    Barreiro => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Barreiro)),
    Cascais => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Cascais)),
    Lisboa => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Lisboa)),
    Loures => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Loures)),
    Mafra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Mafra)),
    Moita => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Moita)),
    Montijo => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Montijo)),
    Odivelas => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Odivelas)),
    Oeiras => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Oeiras)),
    Palmela => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Palmela)),
    Seixal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Seixal)),
    Sesimbra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Sesimbra)),
    Setubal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Setubal)),
    Sintra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_Sintra)),
    VilaFrancaDeXira => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_3_IN_VilaFrancaDeXira)),
)

TOTAL_HOUSEHOLDS_WITH_SIZE_4 = Int64(round(MODEL_SCALE * Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_4))
HOUSEHOLDS_WITH_SIZE_4_MAP = Dict(
    Alcochete => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Alcochete)),
    Almada => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Almada)),
    Amadora => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Amadora)),
    Barreiro => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Barreiro)),
    Cascais => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Cascais)),
    Lisboa => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Lisboa)),
    Loures => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Loures)),
    Mafra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Mafra)),
    Moita => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Moita)),
    Montijo => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Montijo)),
    Odivelas => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Odivelas)),
    Oeiras => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Oeiras)),
    Palmela => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Palmela)),
    Seixal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Seixal)),
    Sesimbra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Sesimbra)),
    Setubal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Setubal)),
    Sintra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_Sintra)),
    VilaFrancaDeXira => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_4_IN_VilaFrancaDeXira)),
)

TOTAL_HOUSEHOLDS_WITH_SIZE_GT_5 = Int64(round(MODEL_SCALE * Theoretical_TOTAL_HOUSEHOLDS_WITH_SIZE_GT_5))
HOUSEHOLDS_WITH_SIZE_GT_5_MAP = Dict(
    Alcochete => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Alcochete)),
    Almada => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Almada)),
    Amadora => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Amadora)),
    Barreiro => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Barreiro)),
    Cascais => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Cascais)),
    Lisboa => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Lisboa)),
    Loures => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Loures)),
    Mafra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Mafra)),
    Moita => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Moita)),
    Montijo => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Montijo)),
    Odivelas => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Odivelas)),
    Oeiras => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Oeiras)),
    Palmela => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Palmela)),
    Seixal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Seixal)),
    Sesimbra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Sesimbra)),
    Setubal => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Setubal)),
    Sintra => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_Sintra)),
    VilaFrancaDeXira => Int64(round(MODEL_SCALE * Theoretical_HOUSEHOLDS_WITH_SIZE_GT_5_IN_VilaFrancaDeXira)),
)

HOUSEHOLDS_SIZES_MAP = Dict(
    1 => HOUSEHOLDS_WITH_SIZE_1_MAP,
    2 => HOUSEHOLDS_WITH_SIZE_2_MAP,
    3 => HOUSEHOLDS_WITH_SIZE_3_MAP,
    4 => HOUSEHOLDS_WITH_SIZE_4_MAP,
    5 => HOUSEHOLDS_WITH_SIZE_GT_5_MAP,
)

HOME_OWNERS_IN_Alcochete = Int64(round(5085  * MODEL_SCALE))
HOME_OWNERS_IN_Almada = Int64(round(47380 * MODEL_SCALE))
HOME_OWNERS_IN_Amadora = Int64(round(44275 * MODEL_SCALE))
HOME_OWNERS_IN_Barreiro = Int64(round(23487 * MODEL_SCALE))
HOME_OWNERS_IN_Cascais = Int64(round(56436 * MODEL_SCALE))
HOME_OWNERS_IN_Lisboa  = Int64(round(121869 * MODEL_SCALE))
HOME_OWNERS_IN_Loures  = Int64(round(49847 * MODEL_SCALE))
HOME_OWNERS_IN_Mafra = Int64(round(23259 * MODEL_SCALE))
HOME_OWNERS_IN_Moita = Int64(round(18879 * MODEL_SCALE))
HOME_OWNERS_IN_Montijo = Int64(round(14555 * MODEL_SCALE))
HOME_OWNERS_IN_Odivelas = Int64(round(39445 * MODEL_SCALE))
HOME_OWNERS_IN_Oeiras = Int64(round(49136 * MODEL_SCALE))
HOME_OWNERS_IN_Palmela = Int64(round(19771 * MODEL_SCALE))
HOME_OWNERS_IN_Seixal = Int64(round(50723 * MODEL_SCALE))
HOME_OWNERS_IN_Sesimbra = Int64(round(15421 * MODEL_SCALE))
HOME_OWNERS_IN_Setubal = Int64(round(35109 * MODEL_SCALE))
HOME_OWNERS_IN_Sintra = Int64(round(104302 * MODEL_SCALE))
HOME_OWNERS_IN_VilaFrancaDeXira = Int64(round(39619 * MODEL_SCALE))


NOT_HOME_OWNERS_IN_Alcochete = Int64(round(2326 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Almada = Int64(round(28105 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Amadora = Int64(round(29238 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Barreiro = Int64(round(10859 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Cascais = Int64(round(30029 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Lisboa =  Int64(round(120175 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Loures =  Int64(round(31705 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Mafra = Int64(round(9893 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Moita = Int64(round(8610 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Montijo = Int64(round(7549 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Odivelas = Int64(round(20674 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Oeiras = Int64(round(23877 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Palmela = Int64(round(6851 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Seixal = Int64(round(16811 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Sesimbra = Int64(round(5136 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Setubal = Int64(round(16060 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_Sintra = Int64(round(48845 * MODEL_SCALE))
NOT_HOME_OWNERS_IN_VilaFrancaDeXira = Int64(round(16022 * MODEL_SCALE))


NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Alcochete = 85 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Almada = 1426 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Amadora = 1664 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Barreiro = 424 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Cascais = 1321 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Lisboa =  4871 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Loures =  1798 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Mafra = 358 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Moita = 491 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Montijo = 327 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Odivelas = 1060 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Oeiras = 755 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Palmela = 299 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Seixal = 855 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Sesimbra = 235 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Setubal = 677 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_Sintra = 2020 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_10_M2_PER_PERSON_IN_VilaFrancaDeXira = 612 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Alcochete = 146 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Almada = 2020 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Amadora = 2872 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Barreiro = 876 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Cascais = 1822 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Lisboa =  5975 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Loures =  2707 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Mafra = 612 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Moita = 902 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Montijo = 448 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Odivelas = 1827 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Oeiras = 1278 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Palmela = 497 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Seixal = 1467 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Sesimbra = 382 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Setubal = 1073 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_Sintra = 4352 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_15_M2_PER_PERSON_IN_VilaFrancaDeXira = 1191 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Alcochete = 409 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Almada = 5695 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Amadora = 6960 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Barreiro = 2403 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Cascais = 5454 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Lisboa =  18229 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Loures =  6972 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Mafra = 1746 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Moita = 2189 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Montijo = 1319 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Odivelas = 4663 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Oeiras = 4084 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Palmela = 1458 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Seixal = 4299 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Sesimbra = 1170 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Setubal = 3148 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_Sintra = 11761 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_20_M2_PER_PERSON_IN_VilaFrancaDeXira = 3590 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Alcochete = 939 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Almada = 11275 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Amadora = 12615 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Barreiro = 5253 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Cascais = 12159 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Lisboa =  34396 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Loures =  13502 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Mafra = 4129 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Moita = 4489 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Montijo = 3041 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Odivelas = 10025 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Oeiras = 10207 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Palmela = 3571 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Seixal = 9791 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Sesimbra = 3065 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Setubal = 7018 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_Sintra = 25545 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_30_M2_PER_PERSON_IN_VilaFrancaDeXira = 9069 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Alcochete = 1454 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Almada = 14728 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Amadora = 16046 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Barreiro = 7570 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Cascais = 16074 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Lisboa =  45540 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Loures =  16848 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Mafra = 6196 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Moita = 5948 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Montijo = 4571 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Odivelas = 13079 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Oeiras = 14441 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Palmela = 5144 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Seixal = 14352 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Sesimbra = 4196 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Setubal = 10162 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_Sintra = 33444 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_40_M2_PER_PERSON_IN_VilaFrancaDeXira = 12825 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Alcochete = 2205 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Almada = 19231 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Amadora = 16670 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Barreiro = 8327 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Cascais = 22806 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Lisboa =  59223 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Loures =  19980 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Mafra = 10141 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Moita = 6866 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Montijo = 6256 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Odivelas = 15167 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Oeiras = 19248 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Palmela = 7768 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Seixal = 18260 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Sesimbra = 5668 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Setubal = 14028 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_Sintra = 37621 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_60_M2_PER_PERSON_IN_VilaFrancaDeXira = 14769 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Alcochete = 789 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Almada = 8587 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Amadora = 8076 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Barreiro = 4740 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Cascais = 9799 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Lisboa =  30608 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Loures =  8572 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Mafra = 3827 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Moita = 2930 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Montijo = 2302 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Odivelas = 6178 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Oeiras = 8988 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Palmela = 2952 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Seixal = 7178 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Sesimbra = 2215 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Setubal = 5606 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_Sintra = 16054 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_LT_80_M2_PER_PERSON_IN_VilaFrancaDeXira = 5963 * MODEL_SCALE

NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Alcochete = 1384 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Almada = 12523 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Amadora = 8610 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Barreiro = 4753 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Cascais = 17030 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Lisboa =  43202 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Loures =  11173 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Mafra = 6143 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Moita = 3674 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Montijo = 3840 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Odivelas = 8120 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Oeiras = 14012 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Palmela = 4933 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Seixal = 11332 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Sesimbra = 3626 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Setubal = 9457 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_Sintra = 22350 * MODEL_SCALE
NUMBER_OF_HOUSES_WITH_MT_80_M2_PER_PERSON_IN_VilaFrancaDeXira = 7622 * MODEL_SCALE


adjacentZones = Dict(
    Amadora          => [Odivelas, Sintra, Oeiras, Lisboa],
    Cascais          => [Sintra, Oeiras],
    Lisboa           => [Odivelas, Amadora, Oeiras, Loures],
    Loures           => [Odivelas, Sintra, Mafra, Lisboa, VilaFrancaDeXira],
    Mafra            => [Sintra, Loures],
    Odivelas         => [Odivelas, Sintra, Oeiras, Lisboa],
    Oeiras           => [Cascais, Sintra, Amadora, Lisboa],
    Sintra           => [Odivelas, Sintra, Oeiras, Amadora, Cascais, Mafra, Loures],
    VilaFrancaDeXira => [Loures],
    Alcochete        => [Montijo, Palmela],
    Almada           => [Seixal, Sesimbra],
    Barreiro         => [Moita, Montijo, Seixal, Setubal, Sesimbra],
    Moita            => [Montijo, Barreiro, Palmela, Setubal],
    Montijo          => [Palmela, Alcochete, Moita, Barreiro],
    Palmela          => [Montijo, Alcochete, Setubal, Moita, Barreiro],
    Seixal           => [Almada, Barreiro, Sesimbra],
    Sesimbra         => [Setubal, Seixal, Almada, Barreiro],
    Setubal          => [Sesimbra, Barreiro, Palmela]
)


FIRST_QUINTILE_INCOME_IN_Alcochete = 7532 / 12
FIRST_QUINTILE_INCOME_IN_Almada = 6937 / 12
FIRST_QUINTILE_INCOME_IN_Amadora = 6650 / 12
FIRST_QUINTILE_INCOME_IN_Barreiro = 7162 / 12
FIRST_QUINTILE_INCOME_IN_Cascais = 7004 / 12
FIRST_QUINTILE_INCOME_IN_Lisboa = 7308 / 12
FIRST_QUINTILE_INCOME_IN_Loures = 7006 / 12
FIRST_QUINTILE_INCOME_IN_Mafra = 6764 / 12
FIRST_QUINTILE_INCOME_IN_Moita = 6678 / 12
FIRST_QUINTILE_INCOME_IN_Montijo = 6691 / 12
FIRST_QUINTILE_INCOME_IN_Odivelas = 6793 / 12
FIRST_QUINTILE_INCOME_IN_Oeiras = 8424 / 12
FIRST_QUINTILE_INCOME_IN_Palmela = 6780 / 12
FIRST_QUINTILE_INCOME_IN_Seixal = 7126 / 12
FIRST_QUINTILE_INCOME_IN_Sesimbra = 6900 / 12
FIRST_QUINTILE_INCOME_IN_Setubal = 6930 / 12
FIRST_QUINTILE_INCOME_IN_Sintra = 6797 / 12
FIRST_QUINTILE_INCOME_IN_VilaFrancaDeXira = 7604 / 12


SECOND_QUINTILE_INCOME_IN_Alcochete = 10874 / 12
SECOND_QUINTILE_INCOME_IN_Almada = 10294 / 12
SECOND_QUINTILE_INCOME_IN_Amadora = 9713 / 12
SECOND_QUINTILE_INCOME_IN_Barreiro = 10140 / 12
SECOND_QUINTILE_INCOME_IN_Cascais = 10784 / 12
SECOND_QUINTILE_INCOME_IN_Lisboa = 11575 / 12
SECOND_QUINTILE_INCOME_IN_Loures = 9975 / 12
SECOND_QUINTILE_INCOME_IN_Mafra = 10077 / 12
SECOND_QUINTILE_INCOME_IN_Moita = 9517 / 12
SECOND_QUINTILE_INCOME_IN_Montijo = 9772 / 12
SECOND_QUINTILE_INCOME_IN_Odivelas = 9930 / 12
SECOND_QUINTILE_INCOME_IN_Oeiras = 12981 / 12
SECOND_QUINTILE_INCOME_IN_Palmela = 9996 / 12
SECOND_QUINTILE_INCOME_IN_Seixal = 10387 / 12
SECOND_QUINTILE_INCOME_IN_Sesimbra = 10159 / 12
SECOND_QUINTILE_INCOME_IN_Setubal = 10175 / 12
SECOND_QUINTILE_INCOME_IN_Sintra = 9892 / 12
SECOND_QUINTILE_INCOME_IN_VilaFrancaDeXira = 10648 / 12

THIRD_QUINTILE_INCOME_IN_Alcochete = 16169 / 12
THIRD_QUINTILE_INCOME_IN_Almada = 14750 / 12
THIRD_QUINTILE_INCOME_IN_Amadora = 13381 / 12
THIRD_QUINTILE_INCOME_IN_Barreiro = 13662 / 12
THIRD_QUINTILE_INCOME_IN_Cascais = 16480 / 12
THIRD_QUINTILE_INCOME_IN_Lisboa = 18918 / 12
THIRD_QUINTILE_INCOME_IN_Loures = 13702 / 12
THIRD_QUINTILE_INCOME_IN_Mafra = 14539 / 12
THIRD_QUINTILE_INCOME_IN_Moita = 12528 / 12
THIRD_QUINTILE_INCOME_IN_Montijo = 13748 / 12
THIRD_QUINTILE_INCOME_IN_Odivelas = 13918 / 12
THIRD_QUINTILE_INCOME_IN_Oeiras = 20024 / 12
THIRD_QUINTILE_INCOME_IN_Palmela = 14193 / 12
THIRD_QUINTILE_INCOME_IN_Seixal = 14328 / 12
THIRD_QUINTILE_INCOME_IN_Sesimbra = 14009 / 12
THIRD_QUINTILE_INCOME_IN_Setubal = 14297 / 12
THIRD_QUINTILE_INCOME_IN_VilaFrancaDeXira = 14252 / 12
THIRD_QUINTILE_INCOME_IN_Sintra = 13417 / 12


FOURTH_QUINTILE_INCOME_IN_Alcochete = 26716 / 12
FOURTH_QUINTILE_INCOME_IN_Almada = 23502 / 12
FOURTH_QUINTILE_INCOME_IN_Amadora = 20882 / 12
FOURTH_QUINTILE_INCOME_IN_Barreiro = 20486 / 12
FOURTH_QUINTILE_INCOME_IN_Cascais = 27978 / 12
FOURTH_QUINTILE_INCOME_IN_Lisboa = 33444 / 12
FOURTH_QUINTILE_INCOME_IN_Loures = 21271 / 12
FOURTH_QUINTILE_INCOME_IN_Mafra = 23325 / 12
FOURTH_QUINTILE_INCOME_IN_Moita = 17930 / 12
FOURTH_QUINTILE_INCOME_IN_Montijo = 21880 / 12
FOURTH_QUINTILE_INCOME_IN_Odivelas = 21633 / 12
FOURTH_QUINTILE_INCOME_IN_Oeiras = 32601 / 12
FOURTH_QUINTILE_INCOME_IN_Palmela = 21810 / 12
FOURTH_QUINTILE_INCOME_IN_Seixal = 21505 / 12
FOURTH_QUINTILE_INCOME_IN_Sesimbra = 20735 / 12
FOURTH_QUINTILE_INCOME_IN_Setubal = 22410 / 12
FOURTH_QUINTILE_INCOME_IN_Sintra = 20169 / 12
FOURTH_QUINTILE_INCOME_IN_VilaFrancaDeXira = 20828 / 12

FOREIGN_RESIDENTS_IN_Alcochete = 1388 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Almada = 16570 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Amadora = 23834 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Barreiro = 5768 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Cascais = 34097 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Lisboa = 108653 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Loures = 21579 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Mafra = 6116 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Moita = 4460 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Montijo = 5848 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Odivelas = 20788 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Oeiras = 14070 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Palmela = 3469 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Seixal = 12904 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Sesimbra = 3290 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Setúbal = 9509 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_Sintra = 42475 * MODEL_SCALE
FOREIGN_RESIDENTS_IN_VilaFrancaDeXira = 9177 * MODEL_SCALE


NEW_FOREIGN_RESIDENTS_IN_Alcochete = 192 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Almada = 2739 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Amadora = 3239 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Barreiro = 997 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Cascais = 4937 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Lisboa = 18664 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Loures = 3337 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Mafra = 1121 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Moita = 782 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Montijo = 903 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Odivelas = 3267 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Oeiras = 2086 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Palmela = 550 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Seixal = 2206 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Sesimbra = 510 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Setubal = 1535 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_Sintra = 6077 * MODEL_SCALE
NEW_FOREIGN_RESIDENTS_IN_VilaFrancaDeXira = 1141 * MODEL_SCALE


BIRTH_RATE = 9.8/1000
PROBABILITY_OF_BIRTH_IN_Alcochete = 7.9 / 1000
PROBABILITY_OF_BIRTH_IN_Almada = 8.8 / 1000
PROBABILITY_OF_BIRTH_IN_Amadora = 10.0 / 1000
PROBABILITY_OF_BIRTH_IN_Barreiro = 8.3 / 1000
PROBABILITY_OF_BIRTH_IN_Cascais = 8.0 / 1000
PROBABILITY_OF_BIRTH_IN_Lisboa = 9.9 / 1000
PROBABILITY_OF_BIRTH_IN_Loures = 10.2 / 1000
PROBABILITY_OF_BIRTH_IN_Mafra = 8.6 / 1000
PROBABILITY_OF_BIRTH_IN_Moita = 10.2 / 1000
PROBABILITY_OF_BIRTH_IN_Montijo = 10.2 / 1000
PROBABILITY_OF_BIRTH_IN_Odivelas = 11.1 / 1000
PROBABILITY_OF_BIRTH_IN_Oeiras = 8.3 / 1000
PROBABILITY_OF_BIRTH_IN_Palmela = 8.4 / 1000
PROBABILITY_OF_BIRTH_IN_Seixal = 8.8 / 1000
PROBABILITY_OF_BIRTH_IN_Sesimbra = 8.2 / 1000
PROBABILITY_OF_BIRTH_IN_Setubal = 8.0 / 1000
PROBABILITY_OF_BIRTH_IN_Sintra = 9.6 / 1000
PROBABILITY_OF_BIRTH_IN_VilaFrancaDeXira = 8.9 / 1000

MORTALITY_RATE = 10.9 / 1000
PROBABILITY_OF_DEATH_IN_Alcochete = 8.6 / 1000
PROBABILITY_OF_DEATH_IN_Almada = 12.5 / 1000
PROBABILITY_OF_DEATH_IN_Amadora = 11.1 / 1000
PROBABILITY_OF_DEATH_IN_Barreiro = 13.7 / 1000
PROBABILITY_OF_DEATH_IN_Cascais = 11.2 / 1000
PROBABILITY_OF_DEATH_IN_Lisboa = 14.1 / 1000
PROBABILITY_OF_DEATH_IN_Loures = 11.5 / 1000
PROBABILITY_OF_DEATH_IN_Mafra = 9.1 / 1000
PROBABILITY_OF_DEATH_IN_Moita = 12.9 / 1000
PROBABILITY_OF_DEATH_IN_Montijo = 11.5 / 1000
PROBABILITY_OF_DEATH_IN_Odivelas = 10.6 / 1000
PROBABILITY_OF_DEATH_IN_Oeiras = 10.9 / 1000
PROBABILITY_OF_DEATH_IN_Palmela = 13.0 / 1000
PROBABILITY_OF_DEATH_IN_Seixal = 10.5 / 1000
PROBABILITY_OF_DEATH_IN_Sesimbra = 10.7 / 1000
PROBABILITY_OF_DEATH_IN_Setubal = 13.6 / 1000
PROBABILITY_OF_DEATH_IN_Sintra = 9.1 / 1000
PROBABILITY_OF_DEATH_IN_VilaFrancaDeXira = 9.8 / 1000

MIGRATION_RATE_IN_Alcochete = 177 * MODEL_SCALE
MIGRATION_RATE_IN_Almada = 3810 * MODEL_SCALE
MIGRATION_RATE_IN_Amadora = 4629 * MODEL_SCALE
MIGRATION_RATE_IN_Barreiro = 1308 * MODEL_SCALE
MIGRATION_RATE_IN_Cascais = 5774 * MODEL_SCALE
MIGRATION_RATE_IN_Lisboa = 25169 * MODEL_SCALE
MIGRATION_RATE_IN_Loures = 4544 * MODEL_SCALE
MIGRATION_RATE_IN_Mafra = 1284 * MODEL_SCALE
MIGRATION_RATE_IN_Moita = 1063 * MODEL_SCALE
MIGRATION_RATE_IN_Montijo = 1164 * MODEL_SCALE
MIGRATION_RATE_IN_Odivelas = 4738 * MODEL_SCALE
MIGRATION_RATE_IN_Oeiras = 2762 * MODEL_SCALE
MIGRATION_RATE_IN_Palmela = 609 * MODEL_SCALE
MIGRATION_RATE_IN_Seixal = 2881 * MODEL_SCALE
MIGRATION_RATE_IN_Sesimbra = 543 * MODEL_SCALE
MIGRATION_RATE_IN_Setubal = 2001 * MODEL_SCALE
MIGRATION_RATE_IN_Sintra = 7733 * MODEL_SCALE
MIGRATION_RATE_IN_VilaFrancaDeXira = 1628 * MODEL_SCALE


PROBABILITY_OF_DIVORCE_IN_Alcochete = 2.3 / 1000
PROBABILITY_OF_DIVORCE_IN_Almada = 1.6 / 1000
PROBABILITY_OF_DIVORCE_IN_Amadora = 1.6 / 1000
PROBABILITY_OF_DIVORCE_IN_Barreiro = 1.7 / 1000
PROBABILITY_OF_DIVORCE_IN_Cascais = 1.8 / 1000
PROBABILITY_OF_DIVORCE_IN_Lisboa = 1.4 / 1000
PROBABILITY_OF_DIVORCE_IN_Loures = 1.4 / 1000
PROBABILITY_OF_DIVORCE_IN_Mafra = 1.8 / 1000
PROBABILITY_OF_DIVORCE_IN_Moita = 1.9 / 1000
PROBABILITY_OF_DIVORCE_IN_Montijo = 1.6 / 1000
PROBABILITY_OF_DIVORCE_IN_Odivelas = 1.5 / 1000
PROBABILITY_OF_DIVORCE_IN_Oeiras = 1.4 / 1000
PROBABILITY_OF_DIVORCE_IN_Palmela = 1.9 / 1000
PROBABILITY_OF_DIVORCE_IN_Seixal = 1.9 / 1000
PROBABILITY_OF_DIVORCE_IN_Sesimbra = 1.7 / 1000
PROBABILITY_OF_DIVORCE_IN_Setubal = 2.0 / 1000
PROBABILITY_OF_DIVORCE_IN_Sintra = 1.7 / 1000
PROBABILITY_OF_DIVORCE_IN_VilaFrancaDeXira = 1.7 / 1000

RATIO_OF_FERTILE_WOMEN = 42.1 / 100
RATIO_OF_FERTILE_WOMEN_IN_Alcochete = 44.8 / 100
RATIO_OF_FERTILE_WOMEN_IN_Almada = 40.3 / 100
RATIO_OF_FERTILE_WOMEN_IN_Amadora = 42.1 / 100
RATIO_OF_FERTILE_WOMEN_IN_Barreiro = 40.1 / 100
RATIO_OF_FERTILE_WOMEN_IN_Cascais = 39.6 / 100
RATIO_OF_FERTILE_WOMEN_IN_Lisboa = 41.5 / 100
RATIO_OF_FERTILE_WOMEN_IN_Loures = 41.8 / 100
RATIO_OF_FERTILE_WOMEN_IN_Mafra = 45.2 / 100
RATIO_OF_FERTILE_WOMEN_IN_Moita = 41.7 / 100
RATIO_OF_FERTILE_WOMEN_IN_Montijo = 45.2 / 100
RATIO_OF_FERTILE_WOMEN_IN_Odivelas = 43.1 / 100
RATIO_OF_FERTILE_WOMEN_IN_Oeiras = 40.0 / 100
RATIO_OF_FERTILE_WOMEN_IN_Palmela = 42.7 / 100
RATIO_OF_FERTILE_WOMEN_IN_Seixal = 42.4 / 100
RATIO_OF_FERTILE_WOMEN_IN_Sesimbra = 43.5 / 100
RATIO_OF_FERTILE_WOMEN_IN_Setubal = 40.6 / 100
RATIO_OF_FERTILE_WOMEN_IN_Sintra = 44.1 / 100
RATIO_OF_FERTILE_WOMEN_IN_VilaFrancaDeXira = 44.4 / 100

0,66
1,36
0,45
0,74
0,56
0,29
0,95
0,47
0,80
1,15
1,52
0,64
0,76
1,89
1,00
1,76
-0,06
0,21
0,18
