
# EXPENSES_MINIMUM_VALUE = []
# EXPENSES_EXTRA_MINIMUM = []
# EXPENSES_EXTRA_OFFSET = []

# GREEDINESS_AVERAGE=[1.15, 1.2]
# GREEDINESS_STDEV=[0.1, 0.05]
# INCOME_MULTIPLICATION_FACTOR=[1.4, 1.5, 1.6, 2.0, 2.5]

# HOUSE_SEARCH_OBFUSCATION_FACTOR=[0.7, 0.65, 0.75]
# HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL=[]
# HOUSE_PRICE_REDUCTION_FACTOR=[0.01, 0.005]


def print_command(
    EXPENSES_MINIMUM_VALUE = "400",
    EXPENSES_EXTRA_MINIMUM = "0.4",
    EXPENSES_EXTRA_OFFSET = "0.25",
    GREEDINESS_AVERAGE = "1.1",
    GREEDINESS_STDEV = "0.1",
    INCOME_MULTIPLICATION_FACTOR = "1.0",
    HOUSE_SEARCH_OBFUSCATION_FACTOR = "0.6",
    HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL = "0.6",
    HOUSE_PRICE_REDUCTION_FACTOR = "0.01",
    INITIAL_WEALTH_PER_PERCENTILE=30,
    INITIAL_WEALTH_PER_AGE=10,
    INITIAL_WEALTH_MULTIPLICATION_AVERAGE = 12.0,
    INITIAL_WEALTH_MULTIPLICATION_STDEV = 6.0
):
    command = "python generateExogenousVariables.py %s %s %s %s %s %s %s %s %s %s %s %s %s"\
                % (
                EXPENSES_MINIMUM_VALUE,
                EXPENSES_EXTRA_MINIMUM,
                EXPENSES_EXTRA_OFFSET,
                GREEDINESS_AVERAGE,
                GREEDINESS_STDEV,
                INCOME_MULTIPLICATION_FACTOR,
                HOUSE_SEARCH_OBFUSCATION_FACTOR,
                HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL,
                HOUSE_PRICE_REDUCTION_FACTOR,
                INITIAL_WEALTH_PER_PERCENTILE,
                INITIAL_WEALTH_PER_AGE,
                INITIAL_WEALTH_MULTIPLICATION_AVERAGE,
                INITIAL_WEALTH_MULTIPLICATION_STDEV
                )
    print(command)
    print("time julia --threads 8 economy.jl")

print_command()
print_command(INITIAL_WEALTH_PER_PERCENTILE=70, INITIAL_WEALTH_PER_AGE=40, INITIAL_WEALTH_MULTIPLICATION_AVERAGE=12.0, INITIAL_WEALTH_MULTIPLICATION_STDEV=6.0)
print_command(INITIAL_WEALTH_PER_PERCENTILE=80, INITIAL_WEALTH_PER_AGE=40, INITIAL_WEALTH_MULTIPLICATION_AVERAGE=12.0, INITIAL_WEALTH_MULTIPLICATION_STDEV=6.0)
print_command(INITIAL_WEALTH_PER_PERCENTILE=80, INITIAL_WEALTH_PER_AGE=60, INITIAL_WEALTH_MULTIPLICATION_AVERAGE=12.0, INITIAL_WEALTH_MULTIPLICATION_STDEV=6.0)
print_command(INITIAL_WEALTH_PER_PERCENTILE=60, INITIAL_WEALTH_PER_AGE=30, INITIAL_WEALTH_MULTIPLICATION_AVERAGE=18.0, INITIAL_WEALTH_MULTIPLICATION_STDEV=9.0)

