import sys
template = """
EXPENSES_MINIMUM_VALUE = %s
EXPENSES_EXTRA_MINIMUM = %s
EXPENSES_EXTRA_OFFSET = %s

GREEDINESS_AVERAGE=%s
GREEDINESS_STDEV=%s

INCOME_MULTIPLICATION_FACTOR=%s

HOUSE_SEARCH_OBFUSCATION_FACTOR=%s
HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL=%s
HOUSE_PRICE_REDUCTION_FACTOR=%s
INITIAL_WEALTH_PER_PERCENTILE=%s
INITIAL_WEALTH_PER_AGE=%s
INITIAL_WEALTH_MULTIPLICATION_AVERAGE = %s
INITIAL_WEALTH_MULTIPLICATION_STDEV = %s
"""

with open("calibrationTable.jl", "w") as f:
    f.write(template % tuple([arg for arg in sys.argv[1:]]))