
# EXPENSES_MINIMUM_VALUE = []
# EXPENSES_EXTRA_MINIMUM = []
# EXPENSES_EXTRA_OFFSET = []

# GREEDINESS_AVERAGE=[1.15, 1.2]
# GREEDINESS_STDEV=[0.1, 0.05]
# INCOME_MULTIPLICATION_FACTOR=[1.4, 1.5, 1.6, 2.0, 2.5]

# HOUSE_SEARCH_OBFUSCATION_FACTOR=[0.7, 0.65, 0.75]
# HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL=[]
# HOUSE_PRICE_REDUCTION_FACTOR=[0.01, 0.005]


def print_command(
    EXPENSES_MINIMUM_VALUE = "400",
    EXPENSES_EXTRA_MINIMUM = "0.3",
    EXPENSES_EXTRA_OFFSET = "0.40",
    GREEDINESS_AVERAGE = "1.05",
    GREEDINESS_STDEV = "0.05",
    GREEDINESS_AVERAGE_FOR_RENTAL = "1.1",
    GREEDINESS_STDEV_FOR_RENTAL = "0.05",
    INCOME_MULTIPLICATION_FACTOR = "1.0",
    HOUSE_SEARCH_OBFUSCATION_FACTOR = "0.7",
    HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL = "0.7",
    HOUSE_PRICE_REDUCTION_FACTOR = "0.01",
    INITIAL_WEALTH_PER_PERCENTILE=70,
    INITIAL_WEALTH_PER_AGE=45,
    INITIAL_WEALTH_MULTIPLICATION_AVERAGE = 12.0,
    INITIAL_WEALTH_MULTIPLICATION_STDEV = 3.0
):
    command = "python generateExogenousVariables.py %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s"\
                % (
                EXPENSES_MINIMUM_VALUE,
                EXPENSES_EXTRA_MINIMUM,
                EXPENSES_EXTRA_OFFSET,
                GREEDINESS_AVERAGE,
                GREEDINESS_STDEV,
                GREEDINESS_AVERAGE_FOR_RENTAL,
                GREEDINESS_STDEV_FOR_RENTAL,
                INCOME_MULTIPLICATION_FACTOR,
                HOUSE_SEARCH_OBFUSCATION_FACTOR,
                HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL,
                HOUSE_PRICE_REDUCTION_FACTOR,
                INITIAL_WEALTH_PER_PERCENTILE,
                INITIAL_WEALTH_PER_AGE,
                INITIAL_WEALTH_MULTIPLICATION_AVERAGE,
                INITIAL_WEALTH_MULTIPLICATION_STDEV
                )
    print(command)
    print("./run.sh")

print_command()
print_command(EXPENSES_MINIMUM_VALUE="500", EXPENSES_EXTRA_MINIMUM="0.1")
print_command(EXPENSES_MINIMUM_VALUE="550")
print_command(EXPENSES_MINIMUM_VALUE="450", GREEDINESS_AVERAGE="1.1")
print_command(EXPENSES_MINIMUM_VALUE="500", GREEDINESS_AVERAGE_FOR_RENTAL="1.05")
print_command(EXPENSES_MINIMUM_VALUE="450")
print_command(INCOME_MULTIPLICATION_FACTOR="1.15")
print_command(HOUSE_SEARCH_OBFUSCATION_FACTOR="0.95")

