
const HOUSE_LOCATION_INSTANCES = [Oeiras]

# const NUMBER_OF_HOUSEHOLDS = 75000
const NUMBER_OF_HOUSEHOLDS = sum([THEORETICAL_NUMBER_OF_HOUSES_MAP[location] for location in HOUSE_LOCATION_INSTANCES])
