
EXPENSES_MINIMUM_VALUE = 350
EXPENSES_EXTRA_MINIMUM = 0.1
EXPENSES_EXTRA_OFFSET = 0.40

GREEDINESS_AVERAGE=1.05
GREEDINESS_STDEV=0.05

INCOME_MULTIPLICATION_FACTOR=1.15

HOUSE_SEARCH_OBFUSCATION_FACTOR=0.7
HOUSE_SEARCH_OBFUSCATION_FACTOR_FOR_RENTAL=0.7
HOUSE_PRICE_REDUCTION_FACTOR=0.01
INITIAL_WEALTH_PER_PERCENTILE=70
INITIAL_WEALTH_PER_AGE=45
INITIAL_WEALTH_MULTIPLICATION_AVERAGE = 12.0
INITIAL_WEALTH_MULTIPLICATION_STDEV = 3.0
